networks:
    nodejs:
        driver: bridge
services:
    vue-client:
        image: node:current-alpine3.16
        ports:
            - '5173:5173'
        expose:
            - '5173'
        stdin_open: true
        volumes:
            - ./vue-client:/var/www/html/vue-client
        networks:
            - nodejs
        entrypoint: ['npm', 'run', 'dev', '--host', '0.0.0.0']
        working_dir: /var/www/html/vue-client
        depends_on:
            - redis

    vue-admin:
        image: node:current-alpine3.16
        ports:
            - '5174:5174'
        expose:
            - '5174'
        stdin_open: true
        volumes:
            - ./admin-client:/var/www/html/admin-client
        networks:
            - nodejs
        entrypoint: ['npm', 'run', 'dev', '--host', '0.0.0.0']
        working_dir: /var/www/html/admin-client
        depends_on:
            - redis

    redis:
        image: node:current-alpine3.16
        volumes:
            - ./server:/var/www/html/server
        ports:
            - '5000:5000'
        environment:
            PORT: 5000
            BASE_URL: http://localhost
            REDIS_URL: redisserver
        working_dir: /var/www/html/server
        entrypoint: ['npm', 'run', 'dev', '--host', '0.0.0.0']
        networks:
            - nodejs
        depends_on:
            - redisserver

    redisserver:
        image: redis:latest
        volumes:
            - ./redisdata:/data
        networks:
            - nodejs
